### ISSUE TITLE
Task: Removing Settings class

### ISSUE THREAD

**Issue by frey-perez** [childmindresearch/wristpy#114]
### Description

A bug was discovered in the get_logger function in configs.py with regards to the Settings class. When the logger is created with get_logger, it uses a new settings object, making it impossible to properly log things. The decision has been made to remove the settings class, and set the logging level with the setLogging method. 

The passing of the physical activity levels will also need to be changed to reflect the removal of the Settings class. Logger verbosity arguments should also be added to the cli and orchestrator. 

### Tasks

- [ ] Remove Settings class.
- [ ] Adjust get_logger function.
- [ ] Add arguments to allow the user to set the level through the cli and orchestrator.run() function.
  - CLI verbosity levels should be warning, info, debug. 
- [ ] Adjust the passing of physical activity thresholds to reflect the removal of the Settings class.
  -  Add validation of threshold values again, as the model_validation will no longer be present.

**Comment by Asanto32** [comment]
Note the default values are now (mentioned/discussed over slack):
 L: 0.0563 M: 0.1916 V: 0.6958
And as per the reference this is best suited for 7-11 yr olds.
