### ISSUE TITLE
Task: Implement the Actigraph `agcounts` as another metric to measure physical activity

### ISSUE THREAD

**Issue by Asanto32** [childmindresearch/wristpy#130]
### Description

As an alternative to ENMO, Activity Counts is used by Actigraph as a metric for physical activity. This metric would take in the raw acceleration `Measurement` object as input. The output can be a activity count `Measurement`. 

A python package exist, with the primary functions [here](https://github.com/actigraph/agcounts/blob/b4539ac0d4d5775cb1fbe8c264cc14267cf6512e/agcounts/extract.py#L285) and [here](https://github.com/actigraph/agcounts/blob/b4539ac0d4d5775cb1fbe8c264cc14267cf6512e/agcounts/extract.py#L239). Briefly, data is downsampled to 30Hz, bandpass filtered (using `scipy.signal.lfilter`) and scaled, the data  is rectified and then thresholded, downsampled to 10Hz, and then a `np.cumsum` is used to count the number of activties per epoch.

Note it appears that the downsampling/trimming of data also does some thresholding.

References: 
https://www.nature.com/articles/s41598-022-16003-x

### Tasks

- [x] Implement the resample function
  - [ ] Downsample to 30Hz, if the current sampling rate is not a multiple of 30Hz, this is achieved by upsampling to the nearest multiple of 30Hz, low pass filtering, and then downsampling back to 30 Hz. The downsampling is achieved by simply  discarding every `m-th` sample.
- [x] Implement the bandpass filter: a seventh order IIR filter defined in the paper.
- [x] Rescale, rectify and threshold the signal.
- [x] Non-overlapping window (moving_mean) to downsample to 10Hz
- [x] Find number of activity counts per epoch
