### ISSUE TITLE
Task: Implement WatchData data storage.

### ISSUE THREAD

**Issue by ReinderVosDeWael** [childmindresearch/wristpy#16]
### Description

The InputData class should be refactored to a WatchData class that stores all data inside Measurement classes, each of which contains the underlying measurements and the associated datetimes. 

This should be inside `wristpy/core/models.py`

### Tasks

- [x] Implement a Measurement class. It should:
   - [x] Inherit from pydantic.BaseModel
   - [x] Have an attribute measurements that is a numpy array.
   - [x] Have an attribute time that is a tuple of datetimes.
 - [x] Implement a WatchData class. It should:
    - [x] Inherit from pydantic.BaseModel
   - [x] Have an acceleration attribute that is a Measurement
   - [x] Have lux, battery, capsense, temperature attributes that are Measurement | None

**Comment by ReinderVosDeWael** [comment]
Proposed alteration: time is instead a polars series (due to severe performance degradations without polars); a validator is included on the measurement class to ensure the datatype is a datetime, as mypy cannot catch a faulty datatype inside a polars series.
