### ISSUE TITLE
Task: Reorganize readers

### ISSUE THREAD

**Issue by ReinderVosDeWael** [childmindresearch/wristpy#17]
### Description

The readers need to be rewritten to account for the WatchData class changes and there should be a convenience reader function that selects the correct function based on file extension.

These should all be placed inside `wristpy/io/readers.py`.

### Tasks

- [x] Rewrite read_gt3x to return WatchData and accept a `pathlib.Path | str`.
- [x] Rewrite read_gene_activ to return WatchData and accept a `pathlib.Path | str`.
- [x] Add a `read_watch_data` that takes the same input and output and selects the correct reader based on file extension or raises and error for unknown file extensions.

**Comment by nx10** [comment]
>  Add a read_watch_data that takes the same input and output and selects the correct reader based on file extension or raises and error for unknown file extensions.

This will work for now but not forever - Many watches use .bin as the extension.

**Comment by ReinderVosDeWael** [comment]
Of course they do... @Asanto32 perhaps we want to omit the wrapper read function

**Comment by nx10** [comment]
I can offer adding one to actfast that reads a few bytes and returns the type

**Comment by Asanto32** [comment]
Ahh, I already started with something simple I an remo

**Comment by Asanto32** [comment]
Also, this is what the reader for GGIR looks like

https://github.com/wadpac/GGIR/blob/master/R/g.readaccfile.R

**Comment by Asanto32** [comment]
@ReinderVosDeWael @nx10 if I'm not mistake the actfast readers only work with str. So if I use the wrapper above in `read_watch_data`, we can pass a string directly. This goes against Task 1 and 2, but captures the idea by using the wrapper. Let me know your thoughts.

**Comment by nx10** [comment]
Yeah so far they only work with string, but I will probably make them compatible with [arrows filesystem abstraction](https://arrow.apache.org/docs/python/filesystems.html) then you can directly stream from stuff like S3

Either way just use 

```Python
actfast.read_x_y(str(path))
```

for now.

**Comment by ReinderVosDeWael** [comment]
Yeah I concur with Florian here; you can take in a `pathlib.Path | str` and convert it with `str()` where needed. This means that users of this function (including power end-users) can use all the goodies of pathlib without being bothered by the conversion themselves.

**Comment by nx10** [comment]
> Also, this is what the reader for GGIR looks like, it seems the other watch with .bin is movisens?
> 
> https://github.com/wadpac/GGIR/blob/master/R/g.readaccfile.R

Just for reference from the GGIR docs:


> 2.2 Prepare folder structure
> GGIR works with the following accelerometer brands and formats:
> [GENEActiv](https://activinsights.com/) .bin
> [Axivity](https://axivity.com/) AX3 and AX6 .cwa
> [ActiGraph](https://theactigraph.com/) .csv and .gt3x (.gt3x only the newer format generated with firmware versions above 2.5.0. Serial numbers that start with “NEO” or “MRA” and have firmware version of 2.5.0 or earlier use an older format of the .gt3x file). Note for Actigraph users: If you want to work with .csv exports via the commercial ActiLife software then note that you have the option to export data with timestamps. Please do not do this as this causes memory issues for GGIR. To cope with the absence of timestamps GGIR will calculate timestamps from the sample frequency, the start time and start date as presented in the file header.
> [Movisens](https://www.movisens.com/en/) .bin files with data stored in folders. GGIR expects that each participant’s folder contains at least a file named acc.bin.
> Any other accelerometer brand that generates csv output, see documentation for functions read.myacc.csv and argument rmc.noise in the [GGIR function documentation (pdf)](https://cran.r-project.org/package=GGIR/GGIR.pdf). Note that functionality for the following file formats was part of GGIR but has been deprecated as it required a significant maintenance effort without a clear use case or community support: (1) .bin for the Genea monitor by Unilever Discover, an accelerometer that was used for some studies between 2007 and 2012) .bin, and (2) .wav files as can be exported by the Axivity Ltd OMGUI software. Please contact us if you think these data formats should be facilitated by GGIR again and if you are interested in supporting their ongoing maintenance.
> All accelerometer data that needs to be analysed should be stored in one folder, or subfolders of that folder.
Give the folder an appropriate name, preferable with a reference to the study or project it is related to rather than just ‘data’, because the name of this folder will be used later on as an identifier of the dataset.

( https://cran.r-project.org/web/packages/GGIR/vignettes/GGIR.html )

So it seems that GENEActiv, Movisens, Genea, and Axivity all use the .bin file extension for their different formats
