### ISSUE TITLE
Draft Task: Implement new metrics calculation as metrics.py

### ISSUE THREAD

**Issue by Asanto32** [childmindresearch/wristpy#19]
### Description

Description

Refactor the old `metrics_calc` into `metrics.py`. This refactoring will take into consideration the new structure of the WatchData and Measurement classes. The logic remains the same as previously.

### Tasks

- [ ] Task 1: Modify existing functionality for the new class structures, and match the diagram tree of wristpy.drawio (separate enmo and anglez calculation, and rename)
- [ ] Task 2: Additional option to use ggir_anglez (rolling_median) vs a default (no rolling median)
- [ ] Task 3: Unit tests, ensure that all functions (not just angle_z and enmo) are covered.
