### ISSUE TITLE
Note: Introduction to conftest.py

### ISSUE THREAD

**Issue by ReinderVosDeWael** [childmindresearch/wristpy#36]
### Description

The sample_data dir could be defined via a pytest fixture in a `conftest.py` to make it easily accessible across all tests. This issue is here simply as a reminder for me to introduce this in the first meeting after Adam returns. 

### Tasks

- [x] Introduce the concept of conftest.py
- [x] Introduce the concept of fixtures.
- [x] Make an issue for introducing this.
