### ISSUE TITLE
Task: Write the CLI argument parser

### ISSUE THREAD

**Issue by ReinderVosDeWael** [childmindresearch/wristpy#41]
### Description

Many end-users will use wristpy via a shell. The CLI should allow for this. 

### Tasks

- [ ] Create parse_cli_args() function in wristpy/core/cli.py
  - [ ] This will use argparse to evaluate the following arguments:
    - [ ] the input file 
    - [ ] the output file
    - [ ] start (int|None) for start date (optional, default None)
    - [ ] end (int|None) for end date (optional, default None)
    - [ ] Optional arguments for core/config.py settings
    - [ ] It should return an argparse.NameSpace

Running the code based on these arguments is left to the orchestrator and out of scope for this PR.
