### ISSUE TITLE
Task: Update readers.py to match new data reading from actfast

### ISSUE THREAD

**Issue by Asanto32** [childmindresearch/wristpy#43]
### Description

The latest release of [Actfast](https://github.com/childmindresearch/actfast/tree/main) has made significant changes to the file reading of the raw sensor data. The new `actfast` module only provides a singular `read` function that handles all types of input paths and file extensions (no longer unique readers for .gt3x, .bin, etc.).  The inputs and outputs of readers.py and its function should remain unchanged.

These changes have made the current readers.py non-compliant with the update. This task will be focused on making the necessary changes to readers.py so that wristpy can work with actfast > 1.0.0. This task will also update /tests/unit/test_readers.py

### Tasks

- [ ] Modify readers.py to be compliant with the new `read` from actfast
     - [ ] Modify gt3x_loader to ensure access of timeseries data from actfast dictionary matches current WatchData class
     - [ ] Modify geneActiv_loader to ensure access of timeseries data from actfast dictionary matches current WatchData class
     - [ ] Remove read_watch_data as `actfast` automatically chooses which reader based on extension + sensor type

- [ ] Modify test_readers.py to remove unnecessary tests
