### ISSUE TITLE
Task: Add physical activity thresholding

### ISSUE THREAD

**Issue by ReinderVosDeWael** [childmindresearch/wristpy#55]
### Description

Analysis of time spent at varying levels of physical activity is a powerful and common tool in physical activity research. Wristpy will be able to take acceleration data in user defined epochs and categorized those epochs as either inactive, Light Physical Activity(LIPA), Moderate Physical Activity, or Vigorous Physical Activity (Moderate and Vigorous are often taken together as MVPA). It will then be able to detect bouts of sustained activity at those activity levels. 

### Tasks

- [ ] Implement ENMO thresholding. Classify each epoch into different activity levels. Activity levels should be: Inactivity, Light Physical Activity (LIPA), and Moderate to Vigorous Physical Activity (MVPA).
     - Threshold values should be user defined. 
     - Default values should be  0.03g, 0.1g, 0.5g for light, moderate, and vigorous activity respectively. 
     - epoch length will be user defined. 

- [ ] Bout Detection: The function should then be able to identify periods of continuous activity(bouts). at every activity level. 
     - User determines bout duration range.  
     - User determines fraction of time for which cut-point criteria needs to be met for a bout to be considered at that activity level. E.g. the user can determine that a given bout can be considered light activity as long as 90% of epochs within the bout meet that criteria. 
     - If the fraction of time is less than 100%,  the "allowable" bout-gap can be no larger than 1 minute, the user cannot change this.
     - first and last epoch in a bout need to meet cut-point criteria
     - Number of activity levels cant be changed
     

- [ ] Returns: ? See third note. 

### Freeform Notes
* @Asanto32 For the default threshold values I'm assuming those were in mg when you gave them to me?
* GGIR website mentions  as one of the things that can't be changed: "Order in which bouts are calculated (1 MVPA; 2 inactive; 3 Light)". This struck me as odd, and probably is a result of some idiosyncrasy of their implementation which we shouldn't replicate ? 
*  it looks like GGIR allows the bout duration and fraction of time values to be set individually for each activity level. How do we want to deal with overlaps? I'm specifically thinking about what this means for what form our return value will take. 

_No response_

**Comment by Asanto32** [comment]
> For the default threshold values I'm assuming those were in mg when you gave them to me?

Yeah, what you have matches what I have (but I do have another version that has 3 values for light, two each for moderate and vigorous). Also, MVPA threshold is it's own thing at 0.125 _g_

We should have a discussion about the whole bout thing. I feel like it is added complexity, perhaps it is something to add later and not for the ADHD summer camp?

 To me the simplest implementation is: calculate enmo in 5-second (seems to be a well accepted standard) epochs, calculate which category a given epoch is a member of (inactivity, light, moderate, vigorous). Return that measurement. 

Then we can count/analyze however we see fit (i.e group per day, and then sum the number of bins in each category per day, per hour, or per week, etc.)

> GGIR website mentions as one of the things that can't be changed: "Order in which bouts are calculated (1 MVPA; 2 inactive; 3 Light)". This struck me as odd, and probably is a result of some idiosyncrasy of their implementation which we shouldn't replicate ?

I also was confused by why the order was a problem.

**Comment by Asanto32** [comment]
I believe that the physical activity metrics are calculated in these functions (potentially, these specific sections):
https://github.com/wadpac/GGIR/blob/master/R/g.analyse.R
https://github.com/wadpac/GGIR/blob/master/R/g.getM5L5.R
https://github.com/wadpac/GGIR/blob/9ae4851aca4338ee804a2bddb9e5d5e8dda6855a/R/g.analyse.perday.R#L536
