### ISSUE TITLE
Task: Update package metadata.

### ISSUE THREAD

**Issue by Asanto32** [childmindresearch/wristpy#56]
### Description

The wristpy readme should be updated to match the content and style of other CMI public repos.

### Tasks

- [x] Update readme to include:
  - [x] Description
  - [x] Installation guide
  - [x] Example usage
- [x] Add tutorial
- [x] Update pyproject.toml to accurately reflect package metadata (e.g. authors, description, etcetera...) 
- [x] Update actfast version for `idle_sleep_mode` metadata support
- [x] Add Ruff rule INP001 (or just all INP, only 001 exists). This will ensure we have a `__init__.py` in every subdirectory. 
- [x] Update the SECURITY.md
- [x] Update the CODE_OF_CONDUCT.md
- [x] Add citation + zenodo DOI
- [x] Update activity thresholds + reference in `analytics.py`

### Freeform Notes

Other sections may also be included, this is a short list and summary.
