### ISSUE TITLE
Task: Implement model #14 of the Kaggle leaderboard

### ISSUE THREAD

**Issue by ReinderVosDeWael** [childmindresearch/wristpy#93]
### Description

Message from GreG:

For the GGIR roadmap: integrating the models from the last Kaggle comp on sleep prediction should be on deck among the next things to tackle

So please give some effort to scoping and defining the implementation plan: https://www.kaggle.com/competitions/child-mind-institute-detect-sleep-states/leaderboard

### Tasks

- [x] Scope the required effort and tasks for implementing additional models. 
- [ ] Implement model # 14 of the Kaggle leaderboard
- [ ] Upload model files and make them downloadable
- [ ] Add a flag for installing additional dependencies (torch).

**Comment by ReinderVosDeWael** [comment]
Changed this issue from a scoping issue to a full task.

**Comment by ReinderVosDeWael** [comment]
Task is currently blocked on a high rate of false positives from the model, likely caused by a faulty evaluation in the Kaggle competition not penalizing false positives much.
